"""Reviewed service registry shared by dispatch, health and recovery."""

from dataclasses import asdict, dataclass
from typing import Any

from orchestrator.qadam_resource_locks import ResourceClaims


@dataclass(frozen=True, kw_only=True)
class ServiceDefinition:
    service_id: str
    purpose: str
    cadence_seconds: int
    trigger: str
    ownership: str
    safe_retry_class: str
    recovery_mode: str
    command_sequence: tuple[tuple[str, ...], ...]
    timeout_seconds: int
    dependencies: tuple[str, ...]
    concurrency_group: str
    lock_requirement: str
    safety_mode: str
    prerequisite_artifacts: tuple[str, ...] = ()
    prerequisite_max_age_seconds: int = 21600
    long_running: bool = False
    market_session_only: bool = False
    provider_budget_required: bool = False
    integration_probe_command_sequence: tuple[tuple[str, ...], ...] = ()
    paperops_dependency: bool = False
    latency_sensitive: bool = False
    freshness_deadline_seconds: int | None = None
    read_resources: tuple[str, ...] = ()
    write_resources: tuple[str, ...] = ()
    append_resources: tuple[str, ...] = ()
    generation_artifacts: tuple[str, ...] = ()
    resource_lock_timeout_seconds: int = 30
    wake_on_dependency_advance: bool = True

    def resource_claims(self) -> ResourceClaims:
        return ResourceClaims(
            reads=self.read_resources,
            writes=self.write_resources,
            appends=self.append_resources,
        )

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


SERVICE_DEFINITIONS = (
    ServiceDefinition(
        service_id="source_ingestion",
        purpose="Refresh configured source evidence on provider-safe schedules.",
        cadence_seconds=300,
        trigger="provider_schedule_and_freshness",
        ownership="source_heartbeat_runner",
        safe_retry_class="idempotent_read",
        recovery_mode="safe_revalidate",
        command_sequence=(
            ("scripts/run_source_heartbeat.py", "--once"),
            ("scripts/run_qadam_live_source_refresh.py", "--max-sources", "10"),
            ("scripts/check_qsase_universal_source_price_matrix.py",),
            ("scripts/check_qsase_source_reliability.py",),
            ("scripts/check_qadam_source_provider_capabilities.py",),
            ("scripts/check_qadam_point_in_time_evidence.py",),
            ("scripts/check_qadam_source_capability_registry.py",),
        ),
        timeout_seconds=900,
        dependencies=(),
        concurrency_group="provider_read",
        lock_requirement="research_read_allowed",
        safety_mode="read_only_provider_refresh",
        read_resources=("price_lake",),
        write_resources=("source_lake", "point_in_time_evidence"),
        generation_artifacts=(
            "qadam_source_research_goal_ingestion.json",
            "qadam_source_provider_capabilities_checks.json",
            "qadam_point_in_time_evidence_checks.json",
            "qadam_source_capability_registry.json",
            "qadam_source_capability_registry_checks.json",
        ),
    ),
    ServiceDefinition(
        service_id="historical_source_worker",
        purpose="Resume bounded source-history acquisition from reviewed providers.",
        cadence_seconds=900,
        trigger="incomplete_source_partitions_and_budget",
        ownership="or3_source_history_runner",
        safe_retry_class="interrupted_resumable_job",
        recovery_mode="terminal_aware_bounded_resume",
        command_sequence=(
            (
                "scripts/run_qadam_source_history_acquisition.py",
                "--allow-network",
                "--provider-terms-reviewed",
                "--max-jobs",
                "10",
                "--classify-deferred",
            ),
        ),
        integration_probe_command_sequence=(
            (
                "scripts/run_qadam_source_history_acquisition.py",
                "--provider-terms-reviewed",
                "--max-jobs",
                "1",
                "--classify-deferred",
            ),
        ),
        timeout_seconds=1800,
        dependencies=(),
        concurrency_group="historical_research",
        lock_requirement="research_read_allowed",
        safety_mode="resumable_provider_acquisition",
        long_running=True,
        provider_budget_required=True,
        write_resources=("source_lake",),
        generation_artifacts=("qadam_source_backfill_manifest.json",),
    ),
    ServiceDefinition(
        service_id="market_price_refresh",
        purpose="Refresh paper-market prices during relevant sessions.",
        cadence_seconds=60,
        trigger="market_session_and_instrument_schedule",
        ownership="existing_market_data_adapters",
        safe_retry_class="idempotent_read",
        recovery_mode="safe_revalidate",
        command_sequence=(("scripts/check_alpaca_paper_mirror.py", "--live"),),
        integration_probe_command_sequence=(("scripts/check_alpaca_paper_mirror.py",),),
        timeout_seconds=120,
        dependencies=(),
        concurrency_group="provider_read",
        lock_requirement="paper_read_only_allowed",
        safety_mode="alpaca_paper_get_only",
        market_session_only=True,
        latency_sensitive=True,
        write_resources=("price_lake", "paper_state"),
        generation_artifacts=(
            "qadam_price_backfill_manifest.json",
            "alpaca_paper_mirror.json",
        ),
    ),
    ServiceDefinition(
        service_id="execution_context",
        purpose=(
            "Compile current session, quote, spread, liquidity, volatility, and "
            "provider state for qualified paper setups."
        ),
        cadence_seconds=60,
        trigger="qualified_trigger_or_open_position",
        ownership="canonical_execution_context_service",
        safe_retry_class="idempotent_read",
        recovery_mode="safe_revalidate",
        command_sequence=(("scripts/check_qadam_execution_context.py",),),
        integration_probe_command_sequence=(("scripts/check_qadam_execution_context.py",),),
        timeout_seconds=120,
        # This read-only compiler consumes market_context_packet, not the
        # account mirror. It must publish missing/expired context even when
        # the market-hours mirror job has never run (for example on restart).
        dependencies=(),
        concurrency_group="provider_read",
        lock_requirement="paper_read_only_allowed",
        safety_mode="current_market_context_read_only",
        market_session_only=False,
        latency_sensitive=True,
        read_resources=("price_lake", "paper_state"),
        write_resources=("learning_plane",),
        generation_artifacts=(
            "qadam_execution_contexts.jsonl",
            "qadam_execution_context_summary.json",
            "qadam_execution_context_checks.json",
        ),
    ),
    ServiceDefinition(
        service_id="open_market_conversion",
        purpose=(
            "Run the fresh-clock, same-generation Akber, shadow, risk, Router, "
            "and canonical PaperOps conversion path for current paper setups."
        ),
        cadence_seconds=300,
        trigger="regular_session_or_new_current_trigger",
        ownership="ef11_open_market_conversion_coordinator",
        safe_retry_class="no_automatic_broker_write_retry",
        recovery_mode="guarded_market_conversion",
        command_sequence=(
            (
                "scripts/run_qadam_open_market_conversion.py",
                "--allow-network",
                "--no-paperops",
            ),
        ),
        integration_probe_command_sequence=(
            (
                "scripts/run_qadam_open_market_conversion.py",
                "--broker-disabled-canary",
                "--no-paperops",
            ),
        ),
        timeout_seconds=1800,
        dependencies=("market_price_refresh", "execution_context"),
        concurrency_group="market_conversion_critical",
        lock_requirement="explicit_research_lock_release_required",
        safety_mode="paper_only_same_generation_canonical_paperops",
        market_session_only=True,
        paperops_dependency=True,
        latency_sensitive=True,
        read_resources=(
            "source_lake",
            "score_plane",
            "edge_registry",
        ),
        write_resources=(
            "price_lake",
            "learning_plane",
            "paper_state",
            "dashboard_projection",
        ),
        generation_artifacts=(
            "qadam_market_clock_truth.json",
            "qadam_prestaged_setup_status.json",
            "qadam_open_market_conversion_generation.json",
            "qadam_open_market_conversion_status.json",
            "qadam_ef11_open_market_conversion_certification.json",
        ),
    ),
    ServiceDefinition(
        service_id="pattern_scoring",
        purpose="Score only after point-in-time evidence refresh completes.",
        cadence_seconds=300,
        trigger="new_evidence_cutoff",
        ownership="pattern_score_v3",
        safe_retry_class="deterministic_calculation",
        recovery_mode="safe_revalidate",
        command_sequence=(
            ("scripts/check_qadam_pattern_score_v3.py",),
            ("scripts/run_qadam_pattern_score_tape.py", "--resume"),
        ),
        timeout_seconds=600,
        dependencies=("source_ingestion",),
        concurrency_group="research_cpu",
        lock_requirement="research_read_allowed",
        safety_mode="deterministic_research_only",
        freshness_deadline_seconds=15 * 60,
        prerequisite_artifacts=("qadam_point_in_time_evidence_checks.json",),
        read_resources=("point_in_time_evidence",),
        write_resources=("score_plane",),
        generation_artifacts=(
            "qadam_feature_registry.json",
            "qadam_pattern_score_v3.json",
            "qadam_pattern_score_v3_records.jsonl",
            "qadam_pattern_score_v3_rejections.jsonl",
            "qadam_pattern_score_v3_dashboard_summary.json",
            "qadam_pattern_score_v3_checks.json",
            "qadam_pattern_score_tape_manifest.json",
            "qadam_pattern_score_tape_progress.json",
            "qadam_pattern_score_tape_quality.json",
            "qadam_pattern_score_tape_checks.json",
        ),
    ),
    ServiceDefinition(
        service_id="research_evidence_validation",
        purpose=(
            "Rebuild forward labels, statistical tests, nonlinear review, and the "
            "edge registry in strict dependency order after pattern scoring."
        ),
        cadence_seconds=300,
        trigger="new_pattern_score_or_validation_deadline",
        ownership="research_evidence_validation",
        safe_retry_class="deterministic_calculation",
        recovery_mode="safe_revalidate",
        command_sequence=(
            ("scripts/check_qadam_forward_labels.py",),
            ("scripts/check_qadam_statistical_backtest.py",),
            ("scripts/check_qadam_nonlinear_quantum_value.py",),
            ("scripts/check_qadam_edge_registry.py",),
        ),
        timeout_seconds=1800,
        dependencies=("pattern_scoring",),
        concurrency_group="research_cpu",
        lock_requirement="research_read_allowed",
        safety_mode="ordered_research_validation_only",
        freshness_deadline_seconds=15 * 60,
        prerequisite_artifacts=("qadam_pattern_score_v3_checks.json",),
        read_resources=("source_lake", "price_lake", "score_plane"),
        write_resources=("label_plane", "edge_registry"),
        generation_artifacts=(
            "qadam_forward_labels_checks.json",
            "qadam_statistical_backtest_checks.json",
            "qadam_nonlinear_quantum_value_checks.json",
            "qadam_edge_registry_checks.json",
        ),
    ),
    ServiceDefinition(
        service_id="akber_review",
        purpose=(
            "Refresh exact read-only decision context and form V3 strategy drafts. "
            "The canonical compiler performs the later Akber review."
        ),
        cadence_seconds=300,
        trigger="new_score_and_context",
        ownership="akber_filter_v3",
        safe_retry_class="deterministic_calculation",
        recovery_mode="safe_revalidate",
        command_sequence=(
            ("scripts/check_market_context_packet.py",),
            ("scripts/check_qadam_strategy_translation.py",),
            ("scripts/check_qadam_akber_evidence_fit.py",),
        ),
        timeout_seconds=300,
        dependencies=("research_evidence_validation",),
        concurrency_group="research_cpu",
        lock_requirement="research_read_allowed",
        safety_mode="research_eligibility_only",
        freshness_deadline_seconds=15 * 60,
        prerequisite_artifacts=("qadam_edge_registry_checks.json",),
        read_resources=("edge_registry",),
        write_resources=("price_lake", "learning_plane"),
        generation_artifacts=(
            "market_context_packet.json",
            "qadam_current_event_triggers.jsonl",
            "qadam_current_regime_observations.jsonl",
            "qadam_current_market_dislocations.jsonl",
            "qadam_trigger_factory_summary.json",
            "qadam_trigger_factory_rejections.jsonl",
            "qadam_direction_resolutions.jsonl",
            "qadam_direction_resolution_rejections.jsonl",
            "qadam_direction_retry_queue.jsonl",
            "qadam_emerging_strategy_formations.jsonl",
            "qadam_strategy_translation_summary.json",
            "qadam_strategy_foundry_v3_checks.json",
            "qadam_strategy_drafts_v3.jsonl",
            "qadam_akber_evidence_fit_checks.json",
            "qadam_akber_evidence_profile_policy.json",
        ),
    ),
    ServiceDefinition(
        service_id="qeg_evidence_cycle",
        purpose=(
            "Connect current evidence, experiment memory, graph patterns, strategy "
            "admission, and Akber inputs before forward observation."
        ),
        cadence_seconds=300,
        trigger="new_akber_context_or_graph_freshness_deadline",
        ownership="qadam_temporal_evidence_graph",
        safe_retry_class="deterministic_calculation",
        recovery_mode="safe_revalidate",
        command_sequence=(("scripts/run_qadam_qeg_cycle.py", "--operational"),),
        integration_probe_command_sequence=(("scripts/run_qadam_qeg_cycle.py", "--operational"),),
        timeout_seconds=3600,
        dependencies=("akber_review",),
        concurrency_group="research_cpu",
        lock_requirement="ordered_temporal_graph_write",
        safety_mode="research_only_graph_and_akber_input_projection",
        freshness_deadline_seconds=15 * 60,
        prerequisite_artifacts=("qadam_strategy_foundry_v3_checks.json",),
        read_resources=(
            "source_lake",
            "price_lake",
            "point_in_time_evidence",
            "score_plane",
            "label_plane",
            "edge_registry",
            "paper_state",
        ),
        write_resources=("temporal_graph", "learning_plane"),
        generation_artifacts=(
            "qadam_temporal_graph_manifest.json",
            "qadam_temporal_graph_health.json",
            "qadam_experiment_memory_summary.json",
            "qadam_graph_pattern_candidates.json",
            "qadam_actionability_queue.json",
            "qadam_graph_experiment_bridge.json",
            "qadam_graph_quantum_challenger.json",
            "qadam_current_expectancy_v2.jsonl",
            "qadam_graph_strategy_versions.json",
            "qadam_paper_strategy_admission.json",
            "qadam_qeg_strategy_hypotheses.jsonl",
            "qadam_qeg_decision_evidence_packets.jsonl",
            "qadam_qeg_akber_inputs.jsonl",
            "qadam_qeg_akber_results.jsonl",
            "qadam_graph_active_discovery_funnel.json",
            "qadam_qeg_cycle_summary.json",
        ),
    ),
    ServiceDefinition(
        service_id="qualitative_evidence_cycle",
        purpose=(
            "Acquire bounded approved qualitative evidence, preserve point-in-time "
            "provenance, test source-price relationships, and compile typed lane "
            "contributions without invoking the downstream tradeability compiler."
        ),
        cadence_seconds=900,
        trigger="approved_origin_refresh_or_forward_window_maturity",
        ownership="qualitative_evidence_operator",
        safe_retry_class="interrupted_resumable_job",
        recovery_mode="safe_revalidate",
        command_sequence=(
            (
                "scripts/run_qadam_agent_reach_operator.py",
                "--allow-network",
                "--no-fast-path",
            ),
        ),
        integration_probe_command_sequence=(
            ("scripts/run_qadam_agent_reach_operator.py", "--no-fast-path"),
        ),
        timeout_seconds=1800,
        dependencies=("source_ingestion",),
        concurrency_group="provider_read",
        lock_requirement="bounded_qualitative_evidence_write",
        safety_mode="sandboxed_read_only_research_no_trade_authority",
        freshness_deadline_seconds=30 * 60,
        prerequisite_artifacts=("qadam_point_in_time_evidence_checks.json",),
        read_resources=("price_lake", "paper_state"),
        write_resources=(
            "source_lake",
            "label_plane",
            "edge_registry",
            "temporal_graph",
            "learning_plane",
            "dashboard_projection",
        ),
        generation_artifacts=(
            "qadam_agent_reach_baseline.json",
            "qadam_source_count_contract.json",
            "qadam_qualitative_evidence_gap_map.json",
            "qadam_agent_reach_supply_chain_audit.json",
            "qadam_agent_reach_sandbox_status.json",
            "qadam_external_origin_terms_matrix.json",
            "qadam_external_origin_promotion_ledger.jsonl",
            "qadam_external_document_manifest.jsonl",
            "qadam_external_documents.jsonl",
            "qadam_external_acquisition_status.json",
            "qadam_external_channel_health.json",
            "qadam_external_evidence_security_audit.json",
            "qadam_external_evidence_provenance_audit.json",
            "qadam_qualitative_claims.jsonl",
            "qadam_qualitative_claim_rejections.jsonl",
            "qadam_qualitative_claim_challenges.jsonl",
            "qadam_qualitative_claim_summary.json",
            "qadam_qualitative_graph_summary.json",
            "qadam_qualitative_entity_mappings.jsonl",
            "qadam_qualitative_instrument_mappings.jsonl",
            "qadam_qualitative_history_coverage.json",
            "qadam_qualitative_forward_window_status.json",
            "qadam_qualitative_label_manifest.jsonl",
            "qadam_qualitative_pattern_candidates.jsonl",
            "qadam_qualitative_pattern_rejections.jsonl",
            "qadam_qualitative_backtest_summary.json",
            "qadam_qualitative_quantum_review.json",
            "qadam_qualitative_pattern_score_bridge.json",
            "qadam_qualitative_direction_resolutions.jsonl",
            "qadam_qualitative_strategy_impacts.jsonl",
            "qadam_qualitative_akber_inputs.jsonl",
            "qadam_qualitative_akber_explanations.jsonl",
            "qadam_qualitative_paper_eligibility.json",
            "qadam_prediction_contract_registry.jsonl",
            "qadam_prediction_contracts.jsonl",
            "qadam_prediction_contract_graph.json",
            "qadam_prediction_belief_states.jsonl",
            "qadam_prediction_market_research.json",
            "qadam_prediction_market_paper_registry.json",
            "qadam_prediction_market_quality.json",
            "qadam_prediction_market_consistency_records.jsonl",
            "qadam_prediction_market_cross_asset_signals.jsonl",
            "qadam_prediction_market_intelligence_summary.json",
            "qadam_lane_contributions.jsonl",
            "qadam_lane_authority_inventory.json",
            "qadam_lane_conversion_funnel.json",
            "qadam_lane_blocker_ownership.json",
            "qadam_qualitative_dashboard_summary.json",
            "qadam_qualitative_communications_summary.json",
            "qadam_qualitative_notification_dedupe.jsonl",
            "qadam_agent_reach_operator_status.json",
            "qadam_agent_reach_repair_queue.jsonl",
            "qadam_agent_reach_resource_state.json",
            "qadam_agent_reach_soak_status.json",
        ),
    ),
    ServiceDefinition(
        service_id="power_market_research",
        purpose=(
            "Refresh CAISO power fundamentals and Alpaca proxy evidence, resume a "
            "bounded historical backfill, and test the emerging power strategy."
        ),
        cadence_seconds=1800,
        trigger="power_market_refresh_or_incomplete_partition",
        ownership="power_market_edge_engine",
        safe_retry_class="interrupted_resumable_job",
        recovery_mode="bounded_resume",
        command_sequence=(
            (
                "scripts/run_qadam_power_market_edge_engine.py",
                "--once",
                "--allow-network",
                "--max-partitions",
                "8",
            ),
            ("scripts/check_qadam_power_market_edge_engine.py",),
        ),
        integration_probe_command_sequence=(
            ("scripts/run_qadam_power_market_edge_engine.py", "--once"),
        ),
        timeout_seconds=1200,
        dependencies=(),
        concurrency_group="historical_research",
        lock_requirement="research_read_allowed",
        safety_mode="provider_read_only_emerging_strategy_research",
        long_running=True,
        read_resources=("paper_state",),
        write_resources=("power_market_research",),
        generation_artifacts=(
            "qadam_power_market_edge_engine.json",
            "qadam_power_market_acquisition_manifest.json",
            "qadam_power_market_backtest.json",
            "qadam_power_market_strategy_registry.json",
            "qadam_power_market_pattern_scores.jsonl",
            "qadam_power_market_context.json",
            "qadam_power_market_dashboard_summary.json",
            "qadam_power_market_edge_engine_checks.json",
        ),
    ),
    ServiceDefinition(
        service_id="canonical_tradeability",
        purpose=(
            "Compile V3 and QEG research drafts into one strict same-generation "
            "tradeability envelope and the sole Akber/downstream projection."
        ),
        cadence_seconds=300,
        trigger="new_foundry_or_qeg_draft",
        ownership="canonical_tradeability_compiler",
        safe_retry_class="deterministic_calculation",
        recovery_mode="safe_revalidate",
        command_sequence=(
            ("scripts/check_qadam_tradeability_pipeline.py",),
            ("scripts/check_qadam_akber_filter_v3.py",),
            ("scripts/check_qadam_tradeability_migration.py",),
            ("scripts/check_qadam_tradeability_reachability.py",),
            ("scripts/check_qadam_contract_defect_handling.py",),
        ),
        integration_probe_command_sequence=(
            ("scripts/check_qadam_tradeability_pipeline.py",),
            ("scripts/check_qadam_akber_filter_v3.py",),
            ("scripts/check_qadam_tradeability_reachability.py",),
            ("scripts/check_qadam_contract_defect_handling.py",),
        ),
        timeout_seconds=900,
        dependencies=("qeg_evidence_cycle", "qualitative_evidence_cycle"),
        concurrency_group="research_cpu",
        lock_requirement="ordered_tradeability_compile",
        safety_mode="paper_only_research_compilation_no_authority",
        freshness_deadline_seconds=15 * 60,
        prerequisite_artifacts=("qadam_qeg_cycle_summary.json",),
        read_resources=("temporal_graph", "edge_registry", "price_lake"),
        write_resources=("learning_plane",),
        generation_artifacts=(
            "qadam_tradeability_envelopes.jsonl",
            "qadam_tradeability_envelope_registry.json",
            "qadam_tradeability_envelope_rejections.jsonl",
            "qadam_tradeability_pipeline_checks.json",
            "qadam_tradeability_envelope_checks.json",
            "qadam_tradeability_pipeline_summary.json",
            "qadam_canonical_tradeability_foundry_summary.json",
            "qadam_decision_evidence_packets.jsonl",
            "qadam_decision_evidence_packet_summary.json",
            "qadam_decision_evidence_packet_rejections.jsonl",
            "qadam_generation_integrity_checks.json",
            "qadam_akber_filter_v3_inputs.jsonl",
            "qadam_akber_filter_v3_results.jsonl",
            "qadam_akber_filter_v3_checks.json",
            "qadam_tradeability_contract_defects.jsonl",
            "qadam_contract_defects.jsonl",
            "qadam_contract_repair_requests.jsonl",
            "qadam_contract_defect_summary.json",
            "qadam_tradeability_migration_status.json",
            "qadam_legacy_contract_parity.json",
            "qadam_consumer_migration_audit.json",
            "qadam_deprecation_registry.json",
            "qadam_tradeability_migration_checks.json",
            "qadam_tradeability_reachability_canary.json",
            "qadam_tradeability_reachability_history.jsonl",
            "qadam_tradeability_reachability_checks.json",
            "qadam_contract_self_healing_checks.json",
        ),
    ),
    ServiceDefinition(
        service_id="forward_shadow",
        purpose="Observe eligible hypotheses without orders or proof credit.",
        cadence_seconds=300,
        trigger="new_akber_result_or_due_observation",
        ownership="forward_shadow_runner",
        safe_retry_class="idempotent_read",
        recovery_mode="safe_revalidate",
        command_sequence=(("scripts/run_qadam_forward_shadow.py", "--once", "--allow-network"),),
        timeout_seconds=300,
        dependencies=("canonical_tradeability",),
        concurrency_group="research_cpu",
        lock_requirement="research_read_allowed",
        safety_mode="counterfactual_no_order",
        freshness_deadline_seconds=15 * 60,
        prerequisite_artifacts=("qadam_akber_filter_v3_checks.json",),
        read_resources=("price_lake", "edge_registry"),
        write_resources=("learning_plane",),
        generation_artifacts=("qadam_forward_shadow_checks.json",),
    ),
    ServiceDefinition(
        service_id="portfolio_router_review",
        purpose="Refresh portfolio risk and assign exactly one final Router state.",
        cadence_seconds=300,
        trigger="new_shadow_or_market_context",
        ownership="portfolio_risk_and_router_v3",
        safe_retry_class="deterministic_calculation",
        recovery_mode="safe_revalidate",
        command_sequence=(
            ("scripts/check_qadam_portfolio_risk_engine.py",),
            ("scripts/check_qadam_router_v3_paperops.py",),
            ("scripts/check_qadam_experimental_paper_eligibility.py",),
            ("scripts/check_qadam_multi_setup_paperops.py",),
            ("scripts/check_qadam_decision_generation.py",),
            ("scripts/check_qadam_tradeability_consumers.py",),
            ("scripts/check_qadam_layered_market_judgment.py",),
            ("scripts/check_qadam_risk_router_alignment.py",),
        ),
        timeout_seconds=900,
        dependencies=("forward_shadow",),
        concurrency_group="research_cpu",
        lock_requirement="research_read_allowed",
        safety_mode="single_state_router_no_order",
        freshness_deadline_seconds=15 * 60,
        read_resources=("price_lake", "edge_registry", "paper_state"),
        write_resources=("learning_plane",),
        generation_artifacts=(
            "qadam_router_v3_paperops_checks.json",
            "qadam_router_v3_why_not_trading_now.json",
            "qadam_risk_router_alignment_checks.json",
            "qadam_router_root_cause_summary.json",
            "qadam_multi_setup_paperops.json",
            "qadam_decision_dag_checks.json",
            "qadam_downstream_consumer_checks.json",
            "qadam_decision_generation_manifest.json",
            "qadam_decision_generation_receipts.jsonl",
            "qadam_decision_generation_failures.jsonl",
            "qadam_envelope_akber_decisions.jsonl",
            "qadam_envelope_shadow_decisions.jsonl",
            "qadam_envelope_risk_decisions.jsonl",
            "qadam_envelope_router_decisions.jsonl",
            "qadam_layered_market_judgment_checks.json",
            "qadam_layered_market_judgment_certification.json",
            "qadam_delayed_entry_queue.json",
            "qadam_activity_quality_health.json",
        ),
    ),
    ServiceDefinition(
        service_id="active_discovery_trial",
        purpose=(
            "Record the frozen five-market-session discovery trial after each "
            "generation-consistent Router review."
        ),
        cadence_seconds=300,
        trigger="new_router_generation_or_market_session_progress",
        ownership="active_discovery_trial_observer",
        safe_retry_class="deterministic_calculation",
        recovery_mode="safe_revalidate",
        command_sequence=(
            ("scripts/check_qadam_active_discovery_trial.py",),
            ("scripts/check_qadam_discovery_micro_conversion.py",),
        ),
        timeout_seconds=600,
        dependencies=("portfolio_router_review",),
        concurrency_group="projection",
        lock_requirement="research_read_allowed",
        safety_mode="read_only_trial_observation_no_trade_authority",
        read_resources=(
            "score_plane",
            "edge_registry",
            "learning_plane",
            "paper_state",
        ),
        write_resources=("dashboard_projection",),
        generation_artifacts=(
            "qadam_active_discovery_trial_status.json",
            "qadam_active_discovery_trial_evaluations.jsonl",
            "qadam_active_discovery_trial_sessions.jsonl",
            "qadam_active_discovery_trial_dashboard_summary.json",
            "qadam_active_discovery_conversion_funnel.jsonl",
            "qadam_active_discovery_eligible_days.jsonl",
            "qadam_active_discovery_root_causes.jsonl",
            "qadam_active_discovery_trial_certification.json",
            "qadam_active_discovery_trial_checks.json",
            "qadam_discovery_micro_calibration.json",
            "qadam_discovery_micro_conversion_certification.json",
        ),
    ),
    ServiceDefinition(
        service_id="guarded_paperops",
        purpose="Delegate clean handoffs to the existing guarded Alpaca Paper wrapper.",
        cadence_seconds=1200,
        trigger="explicit_release_and_clean_handoff",
        ownership="canonical_paperops_wrapper_only",
        safe_retry_class="no_automatic_retry",
        recovery_mode="guarded_paperops",
        command_sequence=(("scripts/run_paperops_autonomous_pass.py",),),
        timeout_seconds=1200,
        dependencies=("portfolio_router_review",),
        concurrency_group="paperops",
        lock_requirement="explicit_research_lock_release_required",
        safety_mode="guarded_alpaca_paper_wrapper_only",
        paperops_dependency=True,
        latency_sensitive=True,
        read_resources=("edge_registry", "learning_plane"),
        write_resources=("paper_state", "dashboard_projection"),
        generation_artifacts=("paperops_autonomous_pass_summary.json",),
    ),
    ServiceDefinition(
        service_id="paper_lifecycle_poll",
        purpose="Poll mirrored paper orders and positions without creating new orders.",
        cadence_seconds=300,
        trigger="open_or_pending_paper_lifecycle",
        ownership="paper_lifecycle_poller",
        safe_retry_class="idempotent_read",
        recovery_mode="safe_revalidate",
        command_sequence=(
            ("scripts/check_paperops_paper_lifecycle_poller.py", "--poll-paper-orders"),
            ("scripts/check_qadam_paper_lineage_and_proof.py",),
            ("scripts/check_qadam_lifecycle_control_plane.py",),
        ),
        integration_probe_command_sequence=(
            ("scripts/check_paperops_paper_lifecycle_poller.py",),
            ("scripts/check_qadam_paper_lineage_and_proof.py",),
            ("scripts/check_qadam_lifecycle_control_plane.py",),
        ),
        timeout_seconds=300,
        dependencies=(),
        concurrency_group="paper_read",
        lock_requirement="paper_read_only_allowed",
        safety_mode="alpaca_paper_get_only_no_mutation",
        latency_sensitive=True,
        write_resources=("paper_state",),
        generation_artifacts=(
            "paperops_paper_lifecycle_poller.json",
            "qadam_paper_lineage_and_proof_checks.json",
            "qadam_lifecycle_control_plane_checks.json",
        ),
    ),
    ServiceDefinition(
        service_id="learning_attribution",
        purpose="Refresh outcome attribution and learning records without applying proposals.",
        cadence_seconds=86400,
        trigger="new_outcome_or_daily_deadline",
        ownership="paper_lineage_and_learning_cycle",
        safe_retry_class="deterministic_calculation",
        recovery_mode="safe_revalidate",
        command_sequence=(
            ("scripts/check_qadam_paper_lineage_and_proof.py",),
            ("scripts/check_qadam_experimental_paper_trial.py",),
            ("scripts/check_qadam_outcome_learning_promotion.py",),
            ("scripts/check_qadam_graph_outcome_learning.py",),
            ("scripts/check_qadam_strategy_challenger_tournament.py",),
            ("scripts/check_qadam_learning_cycle_view_model.py",),
            ("scripts/check_qadam_improvement_pipeline_view_model.py",),
        ),
        timeout_seconds=600,
        dependencies=(),
        concurrency_group="research_cpu",
        lock_requirement="research_read_allowed",
        safety_mode="proposal_only_learning",
        read_resources=("edge_registry", "paper_state"),
        write_resources=("temporal_graph", "learning_plane"),
        generation_artifacts=(
            "qadam_temporal_graph_manifest.json",
            "qadam_temporal_graph_health.json",
            "qadam_learning_cycle_dashboard.json",
            "qadam_improvement_pipeline_dashboard.json",
            "qadam_active_discovery_outcomes.jsonl",
            "qadam_gate_attribution_ledger.jsonl",
            "qadam_strategy_promotion_proposals.jsonl",
            "qadam_strategy_admission_decisions.jsonl",
            "qadam_strategy_version_registry.json",
            "qadam_forward_strategy_tournament.json",
            "qadam_forward_research_freeze_registry.json",
            "qadam_outcome_learning_promotion_checks.json",
            "qadam_graph_outcome_learning_summary.json",
            "qadam_strategy_challenger_tournament.json",
        ),
    ),
    ServiceDefinition(
        service_id="dashboard_refresh",
        purpose="Refresh local operator and dashboard-safe projections.",
        cadence_seconds=240,
        trigger="freshness_deadline_or_upstream_receipt",
        ownership="operator_dashboard_projection",
        safe_retry_class="deterministic_calculation",
        recovery_mode="safe_revalidate",
        command_sequence=(
            ("scripts/check_qadam_dashboard_vnext.py",),
            ("scripts/check_qadam_evidence_fit_visibility.py",),
            ("scripts/check_qsase_dashboard_view_model.py",),
            ("scripts/check_qadam_research_progression_health.py",),
            ("scripts/check_qadam_state_root.py",),
            ("scripts/check_qadam_artifact_ownership.py",),
            ("scripts/check_qadam_resource_locks.py",),
            ("scripts/check_qadam_storage_retention.py",),
            ("scripts/check_qadam_operator_dashboard.py",),
            ("scripts/check_qadam_dashboard_epoch_isolation.py",),
            ("scripts/check_qadam_clean_broker_account_preflight.py", "--report-only"),
            ("scripts/check_qadam_quantum_edge_page_view_model.py",),
            ("scripts/check_qadam_tradeability_public_safety.py",),
            ("scripts/check_qadam_catc_real_market_soak.py",),
            ("scripts/check_qadam_catc_dashboard_projection.py",),
            ("scripts/check_qadam_operator_service.py", "--report-only"),
            ("scripts/export_cockpit_status.py", "--no-landing-copy"),
        ),
        integration_probe_command_sequence=(
            ("scripts/check_qadam_dashboard_vnext.py",),
            ("scripts/check_qadam_evidence_fit_visibility.py",),
            ("scripts/check_qadam_research_progression_health.py",),
            ("scripts/check_qadam_operator_dashboard.py",),
            ("scripts/export_cockpit_status.py", "--no-landing-copy"),
        ),
        timeout_seconds=600,
        dependencies=(),
        concurrency_group="projection",
        lock_requirement="research_read_allowed",
        safety_mode="read_only_local_projection",
        freshness_deadline_seconds=360,
        read_resources=(
            "source_lake",
            "price_lake",
            "point_in_time_evidence",
            "score_plane",
            "label_plane",
            "edge_registry",
            "temporal_graph",
            "learning_plane",
            "paper_state",
        ),
        write_resources=("dashboard_projection",),
        generation_artifacts=(
            "qadam_research_progression_health.json",
            "qadam_research_progression_health_history.jsonl",
            "qadam_research_progression_health_checks.json",
            "qadam_operator_dashboard_view_model.json",
            "qadam_evidence_fit_dashboard_summary.json",
            "qadam_strategy_conversion_funnel.json",
            "qadam_material_research_changes.jsonl",
            "qadam_evidence_fit_notification_candidates.jsonl",
            "qadam_evidence_fit_visibility_checks.json",
            "qadam_active_edge_research_certification.json",
            "qadam_active_edge_research_checks.json",
            "qadam_quantum_edge_wave_f_public_view.json",
            "qadam_quantum_edge_wave_g_hybrid_loop.json",
            "qadam_quantum_edge_wave_h_crude_oil_certification.json",
            "qadam_quantum_edge_page.json",
            "qadam_qeg_dashboard_projection.json",
            "qadam_qeg_telegram_projection.json",
            "qadam_qeg_curated_resource_registry.json",
            "qadam_qeg_operator_reliability.json",
            "qadam_qeg_active_discovery_trial.json",
            "qadam_tradeability_compiler_dashboard_summary.json",
            "qadam_agent_gauntlet_dashboard_summary.json",
            "qadam_tradeability_funnel.json",
            "qadam_tradeability_public_safety_audit.json",
            "qadam_canonical_tradeability_compiler_certification.json",
            "qadam_tradeability_soak_status.json",
            "qadam_tradeability_release_manifest.json",
            "qadam_legacy_removal_audit.json",
            "qadam_ctc_implementation_status.json",
            "qadam_canonical_autonomous_tradeability_dashboard_summary.json",
            "qadam_canonical_autonomous_tradeability_telegram_summary.json",
            "qadam_catc_dashboard_projection_checks.json",
            "qadam_catc_real_market_soak.json",
            "cockpit-status.json",
        ),
    ),
    ServiceDefinition(
        service_id="public_status_publication",
        purpose=(
            "Publish the latest completed dashboard projection through the "
            "optional signed public-status bridge."
        ),
        cadence_seconds=240,
        trigger="new_local_dashboard_generation_or_transport_retry",
        ownership="public_status_bridge",
        safe_retry_class="idempotent_read",
        recovery_mode="safe_revalidate",
        command_sequence=(
            ("scripts/publish_qadam_public_status.py",),
            ("scripts/check_qadam_public_status_bridge.py", "--report-only"),
        ),
        timeout_seconds=180,
        dependencies=("dashboard_refresh",),
        concurrency_group="publication",
        lock_requirement="public_safe_transport_only",
        safety_mode="signed_public_status_transport_no_authority",
        freshness_deadline_seconds=480,
        latency_sensitive=True,
        read_resources=("dashboard_projection",),
        write_resources=("public_status_transport",),
        generation_artifacts=("qadam_public_status_bridge_checks.json",),
    ),
    ServiceDefinition(
        service_id="challenger_research",
        purpose=(
            "Run the frozen challenger family weekly; a reviewed material evidence-version "
            "change may request an explicit supervised run."
        ),
        cadence_seconds=604800,
        trigger="weekly_or_explicit_material_dataset_version_change",
        ownership="research_supervisor",
        safe_retry_class="interrupted_resumable_job",
        recovery_mode="bounded_resume",
        command_sequence=(
            ("scripts/check_qadam_forward_labels.py",),
            ("scripts/check_qadam_statistical_backtest.py",),
            ("scripts/check_qadam_nonlinear_quantum_value.py",),
            ("scripts/check_qadam_edge_registry.py",),
            ("scripts/run_qadam_backtest_completion.py",),
            ("scripts/check_qadam_backtest_completion.py",),
        ),
        timeout_seconds=7200,
        dependencies=("pattern_scoring",),
        # The challenger reads and revalidates the score/label plane. Keep it in
        # the same exclusion group as score generation so that plane cannot
        # change underneath a running validation.
        concurrency_group="research_cpu",
        lock_requirement="research_read_allowed",
        safety_mode="resumable_challenger_research",
        prerequisite_artifacts=("qadam_pattern_score_v3_checks.json",),
        long_running=True,
        read_resources=(
            "source_lake",
            "price_lake",
            "point_in_time_evidence",
            "score_plane",
        ),
        write_resources=("label_plane", "edge_registry", "learning_plane"),
        generation_artifacts=(
            "qadam_forward_labels_checks.json",
            "qadam_statistical_backtest_checks.json",
            "qadam_nonlinear_quantum_value_checks.json",
            "qadam_backtest_completion_checks.json",
            "qadam_edge_registry_checks.json",
        ),
        # Pattern scoring refreshes every five minutes even when its evidence
        # population is unchanged. Keep the dependency for ordering and input
        # readiness, but do not turn every routine score receipt into a full
        # challenger backtest. The weekly cadence or an explicit supervised
        # force-due request owns that expensive wake-up.
        wake_on_dependency_advance=False,
    ),
)
